backend/db/migrate/20220817011608_create_property_assessments.rb

fields 1-8 bradley

---

backend/db/migrate/20220817011608_create_property_assessments.rb

add fields 9-16 to property assesment table

---

backend/app/models/property_assessment.rb
backend/db/migrate/20220817011608_create_property_assessments.rb

Managed to successfully perform db:migrate, so hopefully this is good now.

add 41-48 and condition enum

---

backend/README.md
backend/docs/contributing.md
backend/docs/installation.md

Gets a start on README, which should be updated with more information as we make progress.
Resolves #7

Add README

---

frontend/front/src/pages/Public/nav/Drawer.js
frontend/front/src/pages/Public/nav/Nav.js
package-lock.json

Resolves #68 
- Added a CTA button to all views
- Removed the hamburger icon on desktop and tablet
- Removed the 3 menu links from being seen on the blue navbar in mobile
- Moved the hamburger icon from the left side to the right side of the screen in mobile
- Made the hamburger icon clickable and toggle the 3 menu links in mobile
Please review and share any feedback that I can implement.

Fixed Nav bar in mobile view and added Drawer

---

frontend/front/src/pages/Surveyor/SurveyorContainer.js
frontend/front/src/pages/Surveyor/account/Account.js
frontend/front/src/pages/Surveyor/account/AccountDetail.js
frontend/front/src/pages/Surveyor/nav/Nav.js

Resolves #78 
Open questions:
- Can we assume the address is a single string? If it is composed of many parts (street address, city, zip code, etc) then we will need to display each of those parts in sequence, with individual fields available in the future editing mode
- We may need extra padding on the top of the page, depending on what the nav bar looks like
- I'm not a huge fan of the alignment on iPad - what other things will impact it's layout? Do iPad/tablet sized screens get a side drawer menu?
- Which divider line style do we prefer? Gray vs Black? Solid vs dashed?
iPhone:
iPad:
Desktop:

Create account page for surveyor

---

frontend/front/src/App.js
frontend/front/src/pages/AdminView/AdminContainer.js
frontend/front/src/pages/AdminView/dashboard/Dashboard.js
frontend/front/src/pages/AdminView/house/House.js
frontend/front/src/pages/AdminView/nav/Drawer.js
frontend/front/src/pages/AdminView/nav/Nav.js
frontend/front/src/pages/Public/PublicContainer.js
frontend/front/src/pages/viewMenu/AdminView.js

Created a folder for the admin view with navigation, a hamburger menu, and with two tabs (Dashboard and House)

Created Admin View

---

.gitignore
frontend/front/src/App.js
frontend/front/src/pages/Developer/DevContainer.js
frontend/front/src/pages/Developer/home/Home.js
frontend/front/src/pages/Developer/nav/Nav.js
frontend/front/src/pages/Developer/rtkq/ItemAdder.js
frontend/front/src/pages/Developer/rtkq/ItemList.js
frontend/front/src/pages/Developer/rtkq/MiniModal.js
frontend/front/src/pages/Developer/rtkq/ReduxTKQuery.js
frontend/front/src/redux/services.js
frontend/front/src/redux/store.js
node_modules/.yarn-integrity
yarn.lock

Rtkquery sample

---

backend/config/database.yml

- accept Postgres host as an environment variable to allow RDS host URL injection

changes required for AWS hosting

---

frontend/front/README.md

improved readme file, please review.

new directions on readme file

---

frontend/front/README.md
frontend/front/src/pages/Admin/AdminContainer.js
frontend/front/src/pages/Admin/homeProfile/HomeProfile.js

made some fixed to the admin home  file name

Frontend dat

---

frontend/front/package.json
frontend/front/src/pages/Public/Assets/index.css
frontend/front/src/pages/Public/Layout/Footer.js
frontend/front/src/pages/Public/Pages/Home/CardLinksSection.js
frontend/front/src/pages/Public/Pages/Home/CarrouselHero.js
frontend/front/src/pages/Public/Pages/Home/HeroPage.js
frontend/front/src/pages/Public/Pages/Home/Home.js
frontend/front/src/pages/Public/Pages/Home/Testimonial.js
frontend/front/yarn.lock

- Added carousel and testimonial feature to Home page
- Utilized React Material UI Carousel library
- Library source: [React Material UI Carousel](https://learus.github.io/react-material-ui-carousel/)
- Fixed CSS styles in CardLinkSection and Footer components
**Ticket number:** [139](https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/139)

Frontend 139 carrousel testimonial public view home

---

frontend/front/src/pages/Admin/user/UserProfile.js

Reverts codeforboston/urban-league-heat-pump-accelerator#155

Revert "Admin user profile react hook forms"

---

backend/docs/installation.md

Redo of https://github.com/codeforboston/urban-league-heat-pump-accelerator/pull/130
Updating install docs to talk about codespaces

 Updated install docs

---

frontend/front/src/components/SurveyComponent/HeatPumpAddressField.jsx
frontend/front/src/components/SurveyComponent/HeatPumpDropdown.jsx
frontend/front/src/components/SurveyComponent/HeatPumpNameField.jsx
frontend/front/src/components/SurveyComponent/HeatPumpPhoneField.jsx
frontend/front/src/components/SurveyComponent/SurveyComponent.jsx
frontend/front/src/components/SurveyComponent/__tests__/SurveyComponent.test.jsx
frontend/front/src/components/SurveyComponent/__tests__/__snapshots__/SurveyComponent.test.jsx.snap
frontend/front/src/pages/Admin/AdminContainer.js
frontend/front/src/pages/Admin/survey/SurveyError.jsx
frontend/front/src/pages/Admin/survey/SurveyProfile.js
frontend/front/src/pages/Admin/survey/SurveyTable.js
frontend/front/src/pages/Developer/DevContainer.js
frontend/front/src/pages/Public/Pages/SurveyPage/SurveyPage.jsx
frontend/front/src/pages/Public/Pages/SurveyPage/__tests__/__snapshots__/SurveyPage.test.jsx.snap
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/src/redux/apiSlice.js

Content for Admin survey view page, mock out data in rtk-query

---

data-analysis/assignments.py
data-analysis/test_assignments.py

Parameters are a set of surveyors and a set or region_centroids of the same size. Output is a mapping between these two sets.
The ouput is the mapping that minimizes the total distance between each pair.

Create assignment script

---

frontend/front/src/redux/apiSlice.js

- Fixed file path - survey_show.json

Fixed file path - survey_show.json

---

frontend/front/public/index.html
frontend/front/src/pages/Public/Assets/index.css
frontend/front/src/pages/Public/Assets/theme.js
frontend/front/src/pages/Public/Components/ButtonCustom.js
frontend/front/src/pages/Public/Layout/Footer.js
frontend/front/src/pages/Public/Layout/Navbar.js
frontend/front/src/pages/Public/Pages/Home/CardBenefitsSection.js
frontend/front/src/pages/Public/Pages/Home/CardLinksSection.js
frontend/front/src/pages/Public/Pages/Home/HeroPage.js
frontend/front/src/pages/Public/Pages/Home/Home.js
frontend/front/src/pages/Public/Pages/Home/Partners.js
frontend/front/src/pages/Public/Pages/Home/Testimonial.js

- Redesigned About Us and Add Your Voice cards for better presentation.
- Redesigned the Benefits of Heat Pumps cards section.
- Added a button in the Partner section
- Implemented a new font family (Lora) for titles to improve consistency.
- Fixed general CSS issues to enhance the overall design.

Frontend 269 - Public View Design Improvements

---

frontend/front/src/dummyData/jsonServerData/server.js
frontend/front/src/redux/adminViewApiSlice.js
frontend/front/src/redux/apiSlice.js
frontend/front/src/redux/surveyorViewApiSlice.js

Deployed the JSON-server dummy data using the following URL: https://testing-ibhy.onrender.com/.
Resources
https://testing-ibhy.onrender.com/assignments
https://testing-ibhy.onrender.com/homes
https://testing-ibhy.onrender.com/users
https://testing-ibhy.onrender.com/surveys
https://testing-ibhy.onrender.com/homesurvey

Deployed the JSON-server dummy data

---

backend/app/controllers/survey_visits_controller.rb

Add filtering functionality to survey visit endpoint

---

frontend/front/src/pages/Admin/survey/Survey.js

- Addresses Issue: #305 
**Before:**
**After:**
- Removed "+ Create Survey Button" from Admin view in Survey.js

frontend-issue305-remove-create-survey-button

---

frontend/front/src/components/CustomSnackbar.js
frontend/front/src/components/Loader.js
frontend/front/src/pages/Surveyor/dashboard/Dashboard.js
frontend/front/src/pages/viewMenu/ViewMenu.js

- Addresses Issue: #297 
Before:
After:
- Updated dashboard.js and fixed the typo in ViewMenu.js for "Development"

frontend-issue297-remove-JSON-server-status-message

---

frontend/front/src/pages/Public/Components/Typography/Body1.js
frontend/front/src/pages/Public/Components/Typography/TitleHero.js
frontend/front/src/pages/Public/Components/unused-components/README.md
frontend/front/src/pages/Public/Pages/Home/CardLinksSection.js
frontend/front/src/pages/Public/Pages/Home/Home.js
frontend/front/src/pages/Public/Pages/Home/Testimonial.js

I have incorporated the latest features discussed in the previous meeting review.

Frontend 316 public view - Under review

---

frontend/front/src/components/ReCaptcha.js
frontend/front/src/pages/Public/Pages/SurveyPage.js

Something to note is that the front end will send a null token to the back end if anything goes wrong.
Once this is merged we can close #266

Tweak some recaptcha properties

---

backend/app/controllers/survey_responses_controller.rb
backend/app/controllers/survey_visits_controller.rb
backend/app/models/survey_response.rb
backend/app/models/survey_visit.rb
backend/app/views/survey_visits/_survey_visit.json.jbuilder
backend/app/views/surveyors/_surveyor.json.jbuilder
backend/db/migrate/20230519141229_move_completed_to_survey_response.rb
backend/db/migrate/20230519150026_link_survey_visit_to_surveyor.rb
backend/db/schema.rb
backend/spec/factories/survey_responses.rb
backend/spec/factories/survey_visits.rb

When we POST the survey_visit, we want to be able to support also creating the survey response and answers in the same request.

Support creating survey response and answers when POSTing survey_visit

---

frontend/front/public/index.html

Free API - For Spanish translation - Free 100 Thousand Words served per month | globallinkgo.com
Vercel Link: https://urban-league-heat-pump-accelerator-95wjigy2d-thiagobardini.vercel.app/public

API - For Spanish Translation 

---

backend/Gemfile
backend/config/initializers/cors.rb

When the CORS stuff was added, it had some rubocop violations – this resolves them.

Fix rubocop violations

---

frontend/front/src/pages/Admin/survey/SurveyProfile.js
frontend/front/src/pages/Admin/survey/SurveyTable.js
frontend/front/src/pages/Admin/user/UserProfile.js
frontend/front/src/pages/Developer/rtkq/ReduxTKQuery.js
frontend/front/src/pages/Public/Components/AddressValidatorComponent.js
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js

Replaced old loader components with the new custom Loader across the project. Also added error handling to UserProfile.js.

Leo westebbe/frontend 383 standardize loader component

---

backend/.env.example
backend/.gitignore
backend/app/models/jwt_denylist.rb
backend/app/models/user.rb
backend/config/initializers/cors.rb
backend/config/initializers/devise.rb
backend/docker-compose.yml
backend/lib/seeds/test_surveyors.csv
backend/lib/seeds/test_users.csv
frontend/front/src/App.js
frontend/front/src/api/apiSlice.js
frontend/front/src/features/login/Login.js
frontend/front/src/features/login/loginSlice.js
frontend/front/src/features/login/loginUtils.js
frontend/front/src/pages/Admin/AdminContainer.js
frontend/front/src/pages/Surveyor/SurveyorContainer.js

This should unblock the front end team! Although maybe someone else should test it out before this gets merged :sweat_smile:

Various auth tweaks and fixes

---

backend/app/controllers/application_controller.rb
backend/app/controllers/homes_controller.rb
backend/app/models/user.rb
backend/config/initializers/cors.rb
frontend/front/package.json
frontend/front/src/api/apiSlice.js
frontend/front/src/components/SurveyComponent/HeatPumpPhoneField.js
frontend/front/src/components/SurveyComponent/HeatPumpTextField.js
frontend/front/src/features/login/loginUtils.js
frontend/front/src/pages/Admin/user/CreateNewUser.js
frontend/front/src/pages/Admin/user/UserTable.js
frontend/front/yarn.lock

User creation page

---

backend/app/controllers/assignments_surveyors_controller.rb
backend/app/controllers/surveyors_controller.rb
backend/app/views/surveyors/_surveyor.json.jbuilder
backend/config/routes.rb
frontend/front/src/api/apiSlice.js
frontend/front/src/components/CustomSnackbar.js
frontend/front/src/features/breadcrumb/BreadcrumbNav.js
frontend/front/src/features/login/Login.js
frontend/front/src/features/login/loginSlice.js
frontend/front/src/hooks/useDataForSurveyor.js
frontend/front/src/pages/Admin/assignment/AssignTable.js
frontend/front/src/pages/Admin/assignment/Assignment.js
frontend/front/src/pages/Admin/nav/Nav.js
frontend/front/src/pages/Surveyor/SurveyorContainer.js
frontend/front/src/pages/Surveyor/dashboard/AssignmentHome.js
frontend/front/src/pages/Surveyor/dashboard/AssignmentUnit.js
frontend/front/src/pages/Surveyor/dashboard/Dashboard.js
frontend/front/src/pages/Surveyor/dashboard/ListView.js
frontend/front/src/pages/Surveyor/dashboard/OptionMenu.js
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/src/pages/Surveyor/map/MapLinkUnit.js
frontend/front/src/pages/Surveyor/map/mapUtils.js
frontend/front/src/pages/Surveyor/nav/Nav.js

done:
1. assigning/removing assignments to surveyors
2. surveyors can see only their assignments
3. clicking an address takes you to the survey
4. removed in-between pages to streamline things
still needed:
1. the completed field on homes
2. geospatial data on homes

make surveyor workflow functional

---

frontend/front/README.md
frontend/front/docker-builds/Dockerfile
frontend/front/docker-builds/README.md
frontend/front/docker-builds/build_start.sh

Basic production Docker build and run directions in README

---

backend/app/views/surveys/_survey.json.jbuilder
frontend/front/src/components/DateUtils.js
frontend/front/src/components/SurveyComponent/HeatPumpTextField.js
frontend/front/src/components/SurveyQuestionField.js
frontend/front/src/features/breadcrumb/breadcrumbSlice.js
frontend/front/src/hooks/breadcrumbHooks.js
frontend/front/src/pages/Admin/AdminContainer.js
frontend/front/src/pages/Admin/assignment/AssignProfile.js
frontend/front/src/pages/Admin/assignment/AssignTable.js
frontend/front/src/pages/Admin/assignment/Assignment.js
frontend/front/src/pages/Admin/assignment/Unassigned.js
frontend/front/src/pages/Admin/dashboard/Dashboard.js
frontend/front/src/pages/Admin/home/HomeTable.js
frontend/front/src/pages/Admin/home/SurveyVisitProfile.js
frontend/front/src/pages/Admin/survey/SurveyEditorForm.js
frontend/front/src/pages/Admin/survey/SurveyProfile.js
frontend/front/src/pages/Admin/survey/SurveyTable.js
frontend/front/src/pages/Admin/user/UserTable.js

This is all read-only for now, I'll make another issue for editing but I don't think it needs to be prioritized.
Resolves #416

Admin: survey button should show survey structure, not survey responses

---

.github/workflows/test.yml
backend/Dockerfile
backend/app/views/assignments/_assignment.json.jbuilder
backend/docker-compose.yml
frontend/front/src/components/AddressUtils.js
frontend/front/src/pages/Surveyor/dashboard/AssignmentUnit.js
frontend/front/src/pages/Surveyor/map/mapUtils.js

Fixed up the Generate Map button logic based on the back end lat/long changes.

Routing fixes

---

frontend/front/src/pages/Public/Assets/theme.js
frontend/front/src/pages/Public/Components/Button/ButtonWhite.js
frontend/front/src/pages/Public/Components/Typography/Heading2.js
frontend/front/src/pages/Public/Components/Typography/Heading3.js
frontend/front/src/pages/Public/Layout/Footer.js
frontend/front/src/pages/Public/Pages/BenefitsHeatPumps.js
frontend/front/src/pages/Public/Pages/GetInvolved.js
frontend/front/src/pages/Public/Pages/Home/CardBenefitsSection.js
frontend/front/src/pages/Public/Pages/Home/CardLinksSection.js
frontend/front/src/pages/Public/Pages/Home/CarrouselHero.js
frontend/front/src/pages/Public/Pages/Home/HeroPage.js
frontend/front/src/pages/Public/Pages/Home/Home.js
frontend/front/src/pages/Public/Pages/Home/Partners.js
frontend/front/src/pages/Public/Pages/Home/Testimonial.js

Implemented the design suggestions provided by the UX team.
**New link:**
---
**Previous Link**
Get Involved page unresolved and more: https://bhpa-9awy3ckm7-thiagobardini.vercel.app/
**Remains Unresolved**
7/18 - For issues remain unresolved  -  https://bhpa-git-frontend-427-public-view-improvement-thiagobardini.vercel.app/
06/13 - Four issues remain unresolved - https://urban-league-heat-pump-accelerator-git-fro-163dbf-thiagobardini.vercel.app/
**Done**
05/30 - Done - https://urban-league-heat-pump-accelerator-2r7klyrsv-thiagobardini.vercel.app/
05/23 - Done- https://urban-league-heat-pump-accelerator-pr38lxadx-thiagobardini.vercel.app/public
05/16 - Done - https://urban-league-heat-pump-accelerator-git-fro-6cd131-thiagobardini.vercel.app/public

SEP/2023 - Implemented the design suggestions provided by the UX team

---

frontend/front/src/pages/Public/Components/CanonicalizationLoader.js
frontend/front/src/pages/Public/Pages/SurveyPage.js
frontend/front/src/pages/Public/Pages/__tests__/SurveyPage.test.js
frontend/front/yarn.lock

Issue #336 
After submitting a home, a loader component polls the home continuously (every 300ms) until canonicalization process completes on backend.
If `status: canonicalized`, SurveyPage moves on to the survey. If `status:unrecognized` (invalid address) or record is removed (duplicate address), an appropriate error message displays.

336 validate address frontend

---

backend/app/jobs/canonicalize_address_job.rb
backend/spec/jobs/canonicalize_address_job_spec.rb

* Update code to read Pelias data correctly.
* Add test for failing case.
* Fix matching algorithm.

Resolve Homes lose street_number after canonicalization #495

---

frontend/front/src/pages/Surveyor/dashboard/AssignmentUnit.js
frontend/front/src/pages/Surveyor/dashboard/OptionMenu.js

1. Inside the 'AssignmentUnit' component, I added a showOnlyIncomplete useState, created a function to toggle the boolean value, and passed both the state and the toggle function to the 'OptionMenu' component.
2. I implemented a ternary operator to control whether a 'home' should be displayed. This decision is based on whether showOnlyIncomplete is set to true and whether home.complete is also true.
3. In the 'OptionMenu.js' file, I integrated a button that displayes differently based on whether showOnlyIncomplete is set to true or false. When clicked, it toggles the boolean value.
4. To maintain consistency with the rest of the site, I deconstructed the props that were passed into the OptionMenu component."

Feature: Filter Completed Assignments

---

frontend/front/src/pages/Admin/home/Home.js
frontend/front/src/pages/Admin/user/UserProfile.js

- Hide change password feature. since its implemented on the backend yet.
- Remove option to delete user since user won't be remove from database. This cause issues when registering user. Change user status to inactive instead of deleting
- Currently, if you set user status to inactive they still have the ability to login. we will need to check functionality with backend

Frontend 404 admin edit user

---

frontend/front/src/pages/Public/Pages/AboutUs/AboutUs.js
frontend/front/src/pages/Public/Pages/AboutUs/Faq.js
frontend/front/src/pages/Public/locales/en.json
frontend/front/src/pages/Public/locales/es-419.json
frontend/front/src/pages/Public/locales/ht.json
frontend/front/src/pages/Public/locales/pt-BR.json

Adds Faq section to public/about-us with accompanying locales. Locales will need to be reviewed for accuracy.

Frontend issue524 faq

---

frontend/front/src/hooks/breadcrumbHooks.js
frontend/front/src/pages/Admin/home/Home.js
frontend/front/src/pages/Admin/home/HomeTable.js
frontend/front/src/pages/Admin/survey/Survey.js
frontend/front/src/pages/Admin/survey/SurveyTable.js
frontend/front/src/pages/Admin/user/User.js
frontend/front/src/pages/Admin/user/UserTable.js

changed breadcrumb hook data for user case.
fixes #539

Frontend 539 Surveyor Profile link not redirecting

---

backend/app/views/survey_visits/_survey_visit.json.jbuilder

Co-authored-by: mcarre20 <mcarre20@users.noreply.github.com>
Co-authored-by: Andrew <andrewydev6@gmail.com>
Co-authored-by: Mike Lynch <mikelynch@users.noreply.github.com>

Fix survey_visit jbuilder so responses show up for survey visit endpoint

---

frontend/front/src/components/SurveyComponent/HeatPumpDropdown.js
frontend/front/src/components/SurveyComponent/HeatPumpTextField.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/pages/Admin/home/SurveyVisitProfile.js
frontend/front/src/pages/Surveyor/Components/AssignmentDialog.js
frontend/front/src/pages/Surveyor/Components/BackButton.js
frontend/front/src/pages/Surveyor/SurveyorContainer.js
frontend/front/src/pages/Surveyor/dashboard/AssignmentHome.js

- Add dialog to show completed and new survey actions
- Disable fields and cache for completed surveys
Closes #471

Frontend issue 471 view completed surveys

---

frontend/front/src/pages/Admin/assignment/AssignTable.js
frontend/front/yarn.lock

update yarn packages
change row selection props on DataGrid component to match V6 changes. 
https://mui.com/x/migration/migration-data-grid-v5/

updated yarn and row selection function

---

backend/Gemfile.lock
backend/app/controllers/users/passwords_controller.rb
backend/config/database.yml
backend/config/environments/development.rb
backend/config/routes.rb
frontend/front/src/App.js
frontend/front/src/api/apiSlice.js
frontend/front/src/features/login/ForgotPassword.js
frontend/front/src/features/login/Login.js
frontend/front/src/features/login/ResetPassword.js
frontend/front/src/features/login/ResetPasswordError.js
frontend/front/src/util/stringUtils.js

- Add Forgot Password, Reset Password, and Reset Error Components
- Add util for checking email and password
- Add reset password token validation to backend
Closes #546 #403

add validation routes, forgot password, reset password components

---

frontend/front/src/components/SurveyComponent/HeatPumpRadio.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/__tests__/__snapshots__/SurveyComponent.test.js.snap

- Added Radio component and removed Dropdown component from SurveyComponent
- updated SurveyComponent snapshot test
fixes #565

Frontend issue 565 change dropdown to radio

---

frontend/front/src/components/SurveyComponent/HeatPumpRadio.js
frontend/front/src/components/SurveyComponent/HeatPumpTextField.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/__tests__/__snapshots__/SurveyComponent.test.js.snap
frontend/front/src/pages/Surveyor/Components/SurveyorSurvey.js

- Increase readability styles for SurveyorSurvey's SurveyComponent
- Update SurveyComponent's snapshot test

Frontend issue 572 survey font and spacing

---

frontend/front/src/features/login/Login.js
frontend/front/src/features/login/loginSlice.js

User can now see their password in plain text to check for errors

persistent login is now always enable.

---

frontend/front/src/pages/Surveyor/dashboard/AssignmentUnit.js

change text from Generate Map to Generate Route

Update text inside Generate Map Button

---

frontend/front/src/components/SurveyComponent/ConditionalQuestion.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/pages/Surveyor/Components/SurveyorSurvey.js
frontend/front/src/util/surveyUtils.js

- added survey render question rules
- added conditional parent component for questions

Frontend issue 566 logic engine for conditional questions

---

frontend/front/src/pages/Surveyor/map/mapUtils.js

multiple waypoints for Apple Maps was introduce with IOS16 this will not work if Iphone IOS is below 15

fix apple map link

---

frontend/front/package.json
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/SurveyErrorDialog.js
frontend/front/src/pages/Surveyor/dashboard/AssignmentHome.js
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/yarn.lock

- Add an in progress survey status to surveyor dashboard
- Add a delayed survey saved notification as survey is being filled out
- Add survey error submission dialog component 
Closes #563

Issue #563 bad cell service error handling

---

frontend/front/src/api/apiSlice.js
frontend/front/src/components/SurveyComponent/HeatPumpTextField.js
frontend/front/src/pages/Admin/user/CreateNewUser.js

- Changed url and params in api slice to new admin/users endpoint.
- Use redux return values to handle loading and error components.
- Fix rules not being returned to make textfield required when prop present.
Closes #560

560 connect admin users endpoint

---

backend/Gemfile.lock
frontend/front/src/pages/Admin/assignment/AssignProfile.js
frontend/front/src/pages/Admin/assignment/Unassigned.js
frontend/front/src/pages/Admin/home/HomeProfile.js
frontend/front/src/pages/Admin/home/HomeTable.js
frontend/front/src/pages/Admin/user/UserProfile.js
frontend/front/src/pages/Surveyor/account/Account.js

- Remove open prop from instances of customSnackbar as it is unused.
- Update rexml gem

Fix customsnackbar props

---

frontend/front/src/api/apiSlice.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/__tests__/SurveyComponent.test.js
frontend/front/src/components/SurveyComponent/__tests__/__snapshots__/SurveyComponent.test.js.snap
frontend/front/src/pages/Admin/component/AdminSurvey.js
frontend/front/src/pages/Admin/home/SurveyVisitProfile.js
frontend/front/src/pages/Surveyor/SurveyorContainer.js

- Remove admin delete and edit buttons from SurveyComponent
- Remove delete update survey visits mutations from apiSlice
- Update SurveyComponent test

Remove admin delete edit

---

frontend/front/src/util/surveyUtils.js

- Remove country split as backend accepts language with country

remove country split

---

backend/Gemfile.lock
frontend/front/src/features/login/ForgotPassword.js
frontend/front/src/features/login/Login.js

- Update login and forgot password email inputs to use email format.
- Update puma 
Fixes an issue in #613

613 fix login format

---

frontend/front/src/api/apiSlice.js

- Add cache invalidation on new user creation so that admin user table updates

Update cache on new user creation

---

frontend/front/Dockerfile

- Cache front-end dependency installation in dockerfile

Add cache to yarn install

---

frontend/front/src/components/SurveyComponent/HeatPumpCheckbox.js

- Setup checkbox component
Will implement into SurveyComponent.js after #633 and #635 is closed

Add new checkbox component

---

frontend/front/src/api/apiSlice.js
frontend/front/src/pages/Admin/survey/SurveyTable.js

- add CustomToolbar component for DataGrid in SurveyTable
- export button on CustomToolbar takes the place of the default export button and sends GET request to /admin/export endpoint
- handle download and error in apiSlice
- show CustomSnackbar notifications for successful download and error
Closes #666 
https://github.com/user-attachments/assets/4f679025-9f50-468d-b254-c0e7e45c5370

Export button

---

frontend/front/src/pages/Public/Pages/SurveyPage.js
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/src/util/surveyUtils.js

- add language_code to util function and survey submit functions.

Frontend - add language code on survey responses

---

frontend/front/src/pages/Public/Pages/GetHeatPump.js

Fix request a coach link at `/public/get-heat-pump`

fix broken request a coach link

---

frontend/front/src/pages/Surveyor/dashboard/ListView.js

Use assignment.id for `/surveyor/dashboard`'s assignment number for easier referencing.

replace index with assignment id
