codeforboston/urban-league-heat-pump-accelerator

backend/db/migrate/20220817011608_create_property_assessments.rb

Any feedback on datatype choice here would be appreciated. I was mainly using[ this stack overflow post](https://stackoverflow.com/questions/1056323/difference-between-numeric-float-and-decimal-in-sql-server) as a reference for decimal vs float types comparison. 
COM_UNITS     - Number of Commercial Units
RC_UNITS         - Number of Residential/Commercial Units in a condominium building
LAND_SF          - Parcel’s land area in square feet (legal area)
GROSS_AREA   - Gross floor area 
LIVING_AREA   - Living area square footage of the property
LAND_VALUE   - Total assessed land value
BLDG_VALUE    - Total assessed building value
TOTAL_VALUE   - Total assessed value for property

Add fields 25-32 to property assessments table

---

backend/db/migrate/20220817011608_create_property_assessments.rb

This adds my assigned fields to the table. I ran it locally to test, now I will roll it back until all the fields are ready (tried rake `db:migrate --dry-run` and that didn't produce any useful output)
Examined table in postgres and it looks good.
For reference:
MAIL_ADDRESSEE Care of recipient
MAIL_ADDRESS Street address where tax bill is mailed
MAIL_CITY City/neighborhood where tax bill is mailed
MAIL_STATE State where tax bill is mailed
MAIL_ZIPCODE Zip code where tax bill is mailed
RES_FLOOR Number of floors
CD_FLOORN umber of floors of condominium unit 
RES_UNITS Number of Residential units

Adds fields 17-24 to property assessments table

---

backend/db/migrate/20220817011608_create_property_assessments.rb
backend/db/schema.rb

This PR does the following:
* Reorders all the fields to be identical to what is in the source dataset.
* Changes all the names to be consistent with the abbreviations
* * We had some that were modified to be more readable but for data debugging it will be easier if they are the same
* Adds comment to the data key document
* Changes some of the string fields to limit number of chars (for single letter codes)
* Convert values that are in the dataset as 'Y' or 'N' to boolean - will need to handle this conversion on the data import

Reoders fields to match data set. Normalizes all names to match columns.

---

frontend/front/src/features/account/accountSlice.js
frontend/front/src/pages/Surveyor/SurveyorContainer.js
frontend/front/src/pages/Surveyor/account/Account.js
frontend/front/src/pages/Surveyor/account/edit/EditAccount.js
frontend/front/src/redux/store.js

Related to #78 
- Adds `accountSlice` for managing account details
- Account details that are edited in the `EditAccount` form will be shown on the Account page (kept in local page state)
- Editing form has basic validation, requiring a value for all fields, email format validation, and enforcing phone numbers as being 8-11 characters - we should decide which of this validation makes sense
- Update route registration for `/account/edit` page to be more idiomatic
- Connect to API
- Use `setLogOut` action to clear local state when user logs out?
- Decide which fields should be mandatory and consider marking them with asterisks
- Update the look-and-feel to be less similar to the login page
- Update any fields that get changed when the surveyor user model is solidified (e.g. Address will …

Account Edit page

---

frontend/front/src/pages/Admin/userProfile/UserProfile.js

Closes #89 
- CHANGE PASSWORD button hidden while in edit mode.
- EDIT and DELETE buttons are now SAVE and CANCEL while in edit mode.
- Renamed `isDisabled` to `editMode` for clarity.

Change buttons for edit mode

---

frontend/front/src/components/HeatPumpFade.js
frontend/front/src/components/HeatPumpSlide.js
frontend/front/src/components/SurveyComponent/HeatPumpTextField.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/__tests__/SurveyComponent.test.js
frontend/front/src/pages/Admin/survey/SurveyProfile.js
frontend/front/src/pages/Admin/survey/SurveyTable.js
frontend/front/src/pages/Public/Components/AddressValidatorComponent.js
frontend/front/src/pages/Public/Components/PublicSurvey.js
frontend/front/src/pages/Public/Components/ThanksForSubmission.js
frontend/front/src/pages/Public/Pages/SurveyPage.js
frontend/front/src/pages/Surveyor/Components/SubmissionSuccess.js
frontend/front/src/pages/Surveyor/Components/SurveyorSurvey.js
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/src/redux/apiSlice.js
frontend/front/src/util/surveyUtils.js

* added visual transitions between steps of each form
* fixed survey data not displaying properly after editing in admin view
* cache incomplete surveys in local storage until theyre submitted
* refresh list of survey visits with tag invalidation instead of reloading the page :sweat_smile:

Form transitions + caching + bugfixes

---

backend/app/controllers/assignments_controller.rb
backend/app/views/assignments/_assignment.json.jbuilder
backend/db/migrate/20230509010102_add_geocode_to_assignment.rb
backend/db/schema.rb
backend/lib/seeds/test_assignments.csv

Closes #273 
This adds a single column for geocode to the assignment model.

Add geocodes to assignments model

---

backend/app/controllers/assignments_controller.rb
backend/spec/requests/assignments_spec.rb

Parse new surveyor_ids when passed for `PUT` to `/assignments/<id>`.

Allow passing replacement surveyor_ids on assignments update

---

frontend/front/src/api/apiSlice.js
frontend/front/src/pages/Surveyor/Components/SurveyorSurvey.js

In response to issue #365.
Clicking an incomplete home loads Survey 1 and the data for the associated home.
I'm not clear if there should be a capability to load a different survey - there are 4 on the server, but only survey with `id: 1` has any data in the `survey_questions` array. Outside of this branch, the `SurveyorSurvey` component loads survey with `id: 2`, but that one is blank.

Leo westebbe/issue 365 load surveyor survey

---

frontend/front/src/api/apiSlice.js

We no longer need to include the `'.json' suffix for these endpoints because @mikelynch updated the backend `/surveys` endpoints to deliver straight json (#380).

Remove no-longer-need .json suffix from /surveys apiSlice endpoints

---

frontend/front/src/pages/Surveyor/dashboard/AssignmentUnit.js

Addresses on the dashboard view should display unit number to allow surveyor to distinguish from other units at the same address.

Include unit number for addresses on surveyor dashboard view

---

frontend/front/src/pages/Admin/home/SurveyVisitProfile.js
frontend/front/src/util/surveyUtils.js

1. The buildSurveyVisitData function now includes an 'if (answers[key])' statement. So the survey data builds only for questions that have received a response. For example, {1: ‘’, 2: ‘yes’, 3: ‘’} becomes { 2: { survey_question_id: 2, answer: ‘yes'}}.
Note: This created an issue that when the survey only received responses for question 2, and the rest of the survey answers were undefined. And mui wornings went crazy in a loop.
2. The buildDataFromSurveyAnswers function then was modified to handle the missing data that came back. A numberOfQuestions parameter was added to it. For example, if the survey received only answer 2, 1, 3,.... was constructed as {1: ‘’, 2: ‘yes’, 3: ‘’.....}
3. I needed to get the number of survey quetions, so in SurveyVisitProfile.js, I integrated the …

#449: Filter out empty answers before submitting the survey

---

backend/app/views/assignments/_assignment.json.jbuilder
backend/app/views/homes/_home.json.jbuilder

This resolves #487 , undoing a change from ec340dc0421a829d0dab1c79b8bd898e54683324 – which I think was [accidental](https://github.com/codeforboston/urban-league-heat-pump-accelerator/commit/ec340dc0421a829d0dab1c79b8bd898e54683324#diff-00f0d7855d01d32e2d15e16f6067c6f7401f718f6c775c9d732ee26ca25e9aacL4).
I've checked the output, and it seems to be including the array as expected, although in my test instance I don't have any survey_visits to include (so only get an empty array).
I now get:
```bash
(487-add-back-survey_visit_ids) $ curl -s localhost:3000/homes.json | head -c 400
[{"id":2,"street_number":"8","street_name":"WARREN PL","unit_number":null,"city":"ROXBURY","state":"MA","zip_code":"02119","building_type":"TWO-FAM DWELLING","status":"unrecognized","user_added":false,"assignment_i …
```

Add back survey_visit_ids to homes and assignments endpoints

---

frontend/front/src/pages/Admin/AdminContainer.js
frontend/front/src/pages/Admin/assignment/AssignTable.js
frontend/front/src/pages/Admin/survey/SurveyTable.js
frontend/front/src/pages/Admin/user/UserTable.js

- Add horizontal scrolling to users, surveys, assignments tab to prevent small column size on small screen size.
- Add horizontal scrolling to admin tab navigation when content is too wide for small screen screen size.
Closes #540

Frontend issue 540 smart screen column

---

backend/Gemfile
backend/Gemfile.lock

It looks like Bundler audit caught the following issue:
```
Name: rexml
Version: 3.3.2
CVE: CVE-202[4](https://github.com/codeforboston/urban-league-heat-pump-accelerator/actions/runs/10250868096/job/28357566019?pr=589#step:6:4)-41123
GHSA: GHSA-r55c-59qm-vjw6
Criticality: Medium
URL: https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41123
Title: DoS vulnerabilities in REXML
Solution: upgrade to '>= 3.3.3'
```
https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41123/

Fix cve-2024-41123: DoS vulnerabilities in REXML

---

frontend/front/src/hooks/breadcrumbHooks.js

- Fixes an issue in #598 ```Couldn't find Surveyor with 'id'``` error because of mismatched id and user_id

Change UserProfile.js query from user_id to id

---

backend/Gemfile
backend/Gemfile.lock
backend/app/controllers/survey_visits_controller.rb
backend/db/migrate/20240816145140_add_latitude_longitude_to_survey_visits.rb
backend/db/schema.rb
backend/spec/requests/survey_visits_spec.rb

Link to issue: https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/553
This PR will allow the front end to pass the latitude & longitude of the surveyor when they submit the survey visit.
Also heads up - I added the 'pry' gem to the development section of the Gemfile since I use it frequently! Thanks

Allow latitude and longitude to be stored on survey visits

---

backend/app/controllers/surveyors_controller.rb
backend/app/views/surveyors/_surveyor.json.jbuilder
backend/spec/requests/surveyors_spec.rb

The Users page has a column for "role" which is empty because we're not returning the field on the `GET /surveyors` index.  When we return the field on the API the front end does render the value - see screenshot from local environment after code change:

Add role to surveyors index

---

backend/app/views/survey_visits/_survey_visit.json.jbuilder
frontend/front/src/pages/Admin/home/SurveyVisitProfile.js
frontend/front/src/pages/Admin/survey/SurveyTable.js

- Add surveyor and home to survey_visit json response as SurveyVisitProfile and SurveyTable need to make additional api calls to get render data.
- Remove queries and returned values on SurveyVisitProfile and SurveyTable
- Remove updatedAt column as survey cannot be edited anymore.
- Add "Public Submission" to surveyor column when a survey is submitted via Public Survey page (surveyor_id is null).

Remove home queries

---

frontend/front/src/api/apiSlice.js
frontend/front/src/pages/Public/Components/LangPrefDropdown.js
frontend/front/src/pages/Public/Libs/i18n.js
frontend/front/src/util/surveyUtils.js

- Add a langPref validator with 'en-US' as fallback
- Change language codes to capitalized countries
- Call langPref validator before sending langPref param to backend
Fixes #615 
Fixes #616

Create langPref validator, send langPref param to backend

---

backend/.rubocop.yml
backend/app/controllers/surveys_controller.rb
backend/app/models/survey_question.rb
backend/app/policies/surveyor_policy.rb
backend/config/application.rb
backend/spec/requests/assignments_spec.rb
backend/spec/requests/surveys_spec.rb

* Instead of raising StandardError and returning a 500, we return a 404 with some helpfully descriptive JSON text.

Better Error for Not found Language Code

---

frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/__tests__/SurveyComponent.test.js
frontend/front/src/pages/Public/Pages/SurveyPage.js
frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/src/util/surveyUtils.js

- Add lat long params to public survey submission
- Remove location check and saving snackbar for public survey
- Add memory router to survey component tests
Closes #628

Issue 628 - Fix public survey submission

---

frontend/front/src/pages/Surveyor/houseProfile/HouseProfile.js
frontend/front/src/util/surveyUtils.js

- adds a util function that sends all survey answers as an array into backend ```SurveyAnswers``` ```answers``` attribute.
Fixes an issue in #632

add array util function to survey answer submit handler

---

frontend/front/src/pages/Public/Pages/SurveyPage.js

I was testing the Export surveys button and saw that surveys submitted by a surveyor correctly had all the answers, but the answers to public surveys were all blank.
It looks like the recent change made here: https://github.com/codeforboston/urban-league-heat-pump-accelerator/commit/db15b38ca30d2a15a777712f51d1b0da5063378b needs to be extended for public survey answers

Fix answers array public survey

---

backend/app/controllers/survey_visits_controller.rb
backend/app/views/survey_visits/_survey_visit.json.jbuilder
backend/db/migrate/20250324174954_remove_answer_from_survey_answers.rb
backend/db/schema.rb
backend/spec/factories/survey_answers.rb
backend/spec/models/csv_export_helper_spec.rb
backend/spec/requests/survey_visits_spec.rb

https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/646
Frontend has switched to using `survey_answer.answers` so this PR removes the old `survey_answer.answer` field.

646 Remove old answer field

---

backend/app/controllers/survey_visits_controller.rb
backend/app/models/csv_export_helper.rb
backend/app/views/survey_visits/_survey_visit.json.jbuilder
backend/db/migrate/20250420182258_add_language_code_to_survey_responses.rb
backend/db/schema.rb
backend/spec/models/csv_export_helper_spec.rb
backend/spec/models/csv_exporter_spec.rb
backend/spec/requests/admin/exports_spec.rb
backend/spec/requests/survey_visits_spec.rb

Note: Could potentially add validation on survey response that the language code is one of the ones we support - that way we don't end up with a situation where a user inputs a bad value, and then the front end uses it to request the correct language survey later. But meh, doesn't seem too important either way

Add language code to survey responses

---

frontend/front/src/api/apiSlice.js
frontend/front/src/components/SurveyComponent/SurveyComponent.js
frontend/front/src/components/SurveyComponent/SurveyVisitProfile.js
frontend/front/src/components/SurveyComponent/__tests__/SurveyComponent.test.js
frontend/front/src/pages/Admin/AdminContainer.js
frontend/front/src/pages/Admin/component/AdminSurvey.js
frontend/front/src/pages/Admin/home/SurveyVisitProfile.js
frontend/front/src/pages/Public/Components/PublicSurvey.js
frontend/front/src/pages/Surveyor/Components/CompletedSurvey.js
frontend/front/src/pages/Surveyor/Components/SurveyorSurvey.js
frontend/front/src/pages/Surveyor/SurveyorContainer.js
frontend/front/src/util/surveyUtils.js

- add ```survey_mode``` param to backend query and update query calls
- update props for ```SurveyorSurvey```, ```PublicSurvey``` and ```AdminSurvey``` to use their respective language and survey mode settings
- add tests for langPref and surveyMode to ```SurveyComponent```
- remove second arg form ```buildDataFromSurveyAnswers``` util function and remove unneeded ```useGetSurveyStructureQuery``` query for ```SurveyVisitProfile``` as the length of query result is only used. ```useGetSurveyVisitQuery``` can provide same information.

Frontend add survey mode param

---

frontend/front/src/pages/Public/Components/LangPrefDropdown.js
frontend/front/src/pages/Public/Libs/i18n.js

- remove region codes from language picker component
- use more human readable values ("English","Kreyòl","Português","Español") for dropdown

Frontend remove language region code

---

frontend/front/src/pages/Admin/assignment/AssignTable.js
frontend/front/src/pages/Admin/assignment/SurveyorSelect.js

- Added client-side pagination to reduce the initial number rows 
- Removed React state and use the DataGrid's [GridApi](https://v6.mui.com/x/api/data-grid/grid-api/). This seemed to speed up row selection.
- Add an isFetching flag to show loading spinner when making assignment updates/removals.
- Modify the add/remove handlers so that surveyors already assigned are not added again, and only those assigned to the selected assignments can be removed.
- Move `SurveyorSelect.js` into it's own file, now we are preventing `AssignTable.js` to be re-rendered on every surveyor change.

682 assignment table perf fix

---

frontend/front/src/pages/Surveyor/dashboard/ListView.js

- Fix #682 
- Accordion component is not mounted by default so a large number of assignments won’t impact performance.

682 - Perf fix for surveyor assignments page
